# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18uQ2bgmsGiLQnOzCGWn3G4T0e4OEBMib
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/Overall SOA Sheet.csv")

df.columns

df_1 = df[['ClientName','Currency1', 'OutstandingBalance', 'NewStatus']]

df_1=df_1[df_1['NewStatus']=="NOT PAID"]

df_1.Currency1 = df_1.Currency1.fillna('BLANK')

df_1.pivot_table(index='ClientName', columns='Currency1',aggfunc=np.sum)

df_1

