# Generated by Django 4.2.2 on 2023-06-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdata',
            options={},
        ),
    ]
