# Generated by Django 4.2.2 on 2023-06-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0003_alter_testdata_options_and_more'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='testdata',
    #         old_name='InvAmount',
    #         new_name='Invoiceamount',
    #     ),
    # ]
