# Generated by Django 4.2.2 on 2023-06-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0004_rename_invamount_testdata_invoiceamount'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='testdata',
    #         old_name='InvoiceAmountcreditnote',
    #         new_name='Invamtcreditnote',
    #     ),
    # ]
# 